# Generated by Django 4.2.21 on 2025-05-27 20:23

from django.db import migrations
import datetime

def add_initial_data(apps, schema_editor):
    Publisher = apps.get_model('games', 'Publisher')
    Platform = apps.get_model('games', 'Platform')
    Game = apps.get_model('games', 'Game')

    ea = Publisher.objects.create(name="EA", founded_year=1982)
    rockstar = Publisher.objects.create(name="Rockstar Games", founded_year=1998)
    nintendo = Publisher.objects.create(name="Nintendo", founded_year=1889)
    polyphony = Publisher.objects.create(name="Polyphony Digital", founded_year=1998)

    win11 = Platform.objects.create(name="Windows 11", manufacturer="Microsoft")
    switch = Platform.objects.create(name="Nintendo Switch", manufacturer="Nintendo")
    ps3 = Platform.objects.create(name="PlayStation 3", manufacturer="Sony")

    gt5p = Game.objects.create(title="Gran Turismo 5 Prologue", release_date=datetime.date(2007, 12, 13), publisher=polyphony)
    gt5p.platforms.set([ps3])

    gt5 = Game.objects.create(title="Gran Turismo 5", release_date=datetime.date(2010, 11, 24), publisher=polyphony)
    gt5.platforms.set([ps3])

    gt6 = Game.objects.create(title="Gran Turismo 6", release_date=datetime.date(2013, 12, 6), publisher=polyphony)
    gt6.platforms.set([ps3])

    nfs = Game.objects.create(title="Need for Speed The Run", release_date=datetime.date(2011, 11, 15), publisher=ea)
    nfs.platforms.set([ps3, win11])

    mario = Game.objects.create(title="Super Mario Odyssey", release_date=datetime.date(2017, 10, 27), publisher=nintendo)
    mario.platforms.set([switch])

    gta4 = Game.objects.create(title="Grand Theft Auto 4", release_date=datetime.date(2008, 4, 29), publisher=rockstar)
    gta4.platforms.set([ps3, win11])

    gta_sa = Game.objects.create(title="Grand Theft Auto San Andreas", release_date=datetime.date(2004, 10, 26), publisher=rockstar)
    gta_sa.platforms.set([ps3, win11])

class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]
